[book]
authors = ["Chen-Pang He"]
language = "en"
multilingual = false
src = "src"
title = "Taipei Forcing Club System Notes"

[output.html]
additional-css = ["style.css"]
git-repository-url = "https://github.com/jdh8/bridge-systems"
smart-punctuation = true

[preprocessor.yapp]
