# This workflow uses my fork of BML
# https://github.com/jdh8/bml

name: Bridge Bidding Markup Language

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3
      uses: actions/setup-python@v3

    - name: Set up mdbook
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: mdbook mdbook-abbr mdbook-yapp

    - name: Build
      run: |
        pip install git+https://github.com/jdh8/bml.git
        make -j$(nproc)
        mdbook build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        enable_jekyll: true
        exclude_assets: ".github,.gitignore"
