# This workflow uses my fork of BML
# https://github.com/jdh8/bml

name: Bridge Bidding Markup Language

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    
    - name: Install mdbook
      uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: mdbook

    - name: Install mdbook-abbr
      uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: mdbook-abbr

    - name: Install mdbook-yapp
      uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: mdbook-yapp

    - name: Build web pages
      run: |
        pip install git+https://github.com/jdh8/bml.git
        make -j$(nproc)
        mdbook build

    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        enable_jekyll: true
        exclude_assets: ".github,.gitignore"
